### PR TITLE
Fix #1648, #1649: refine algorithm for setting buffer and curve

### LINKED ISSUE #1648: Convolver set buffer algorithm is ill-defined
The [algorithm for setting the convolver buffer](https://webaudio.github.io/web-audio-api/#dom-convolvernode-buffer) says in part:

1. Let new buffer be the AudioBuffer to be assigned to buffer.
1. If new buffer is not null and [[buffer set]] is true, throw an InvalidStateError and abort these steps.

The first step says `new buffer` is an `AudioBuffer`.  Hence in step 2, it can't be null.

I think we should basically copy the algorithm for ABSN set buffer; I think that was the original intent when designing the buffer setting algorithms for ABSN and Convolver.

### PR DESCRIPTION
**Pull request by rtoy**
These algorithms for setting the buffer (ConvovlerNode) and the curve
(WaveShaperNode) should be consistent with how the buffer for an
AudioBufferSourceNode is handled.  The original intent was that you
can only set the buffer(curve) just once, but you can set them to null
as many times as you want, but you can't then set it to a non-null
buffer.

***
<a href="https://pr-preview.s3.amazonaws.com/rtoy/web-audio-api/pull/1653.html" title="Last updated on May 31, 2018, 11:06 PM GMT (301542b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/1653/5e40eb0...rtoy:301542b.html" title="Last updated on May 31, 2018, 11:06 PM GMT (301542b)">Diff</a>

### CODE REVIEW

**Comment by rtoy** [comment]
I was just copying the existing text from the AudioBufferSourceNode. I can change this, but since my current fork is messed up with my auto-deploy I'd prefer to merge this as is and fix it up afterwards if needed.  I don't think the text is wrong but it could, perhaps, be phrased better.

**Comment by mdjp** [comment]
@rtoy I'm happy with that.

**Comment by rtoy** [comment]
Thanks!

**Comment by rtoy** [comment]
#1683 filed to rephrase this if needed.

**Pull request merged**
