### PR TITLE
Fix the build by pinning lxml to the previous version

### PR DESCRIPTION
**Pull request by padenot**
It's doing something weird with buffering, that makes it error out later.

### CODE REVIEW

**Comment by padenot** [comment]
Not amazing:

```sh
./compile.sh: line 17:  3737 Segmentation fault      (core dumped) bikeshed --print=plain -f spec 2>&1 > $BSLOG
```

It seems that bikeshed segfaults on travis.

**Comment by padenot** [comment]
Ok, a quick summary here:

- There was a difference in actual errors vs. expected errors, we saw that the "actual" output was somehow truncated, which made our build error out
- ` tee` and the output redirection was swallowing the problem, which is that `bikeshed` was seg-faulting (found after https://github.com/WebAudio/web-audio-api/pull/1830/commits/730614ac494a073213e09c394b8b739da5950e07) 
- I tried bumping the ubuntu version, this did not help (commit https://github.com/WebAudio/web-audio-api/pull/1830/commits/cfb97bae3073ac940e88dc9a0cfe16cadbe0c283)
- By using `faulthandler` in python, and monkey-patching the `bikeshed` copy that we just installed to enable it (see https://github.com/WebAudio/web-audio-api/pull/1830/commits/2e0ef382e611b3d69b8c3230776a727bca14c2df), we see it's a crash down in bikeshed's `htmlhelpers.py` 

```
++which bikeshed
+sed -i 's/if __main__/import faulthandler\nfaulthandler.enable\(\)\nif __main__/' /home/travis/virtualenv/python2.7.15/bin/bikeshed
++which bikeshed
+PYTHONFAULTHANDLER=1
+python /home/travis/virtualenv/python2.7.15/bin/bikeshed --print=plain -f spec
Fatal Python error: Segmentation fault
Current thread 0x00007f81bb3df700 <python> (most recent call first):
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/htmlhelpers.py", line 416 in childNodes
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/highlight.py", line 237 in colorizeEl
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/highlight.py", line 267 in mergeHighlighting
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/highlight.py", line 133 in highlightEl
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/highlight.py", line 36 in addSyntaxHighlighting
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/Spec.py", line 215 in processDocument
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/Spec.py", line 103 in preprocess
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/cli.py", line 240 in handleSpec
  File "/home/travis/build/WebAudio/web-audio-api/bikeshed/bikeshed/cli.py", line 204 in main
  File "/home/travis/virtualenv/python2.7.15/bin/bikeshed", line 11 in <module>
./compile.sh: line 19:  3015 Segmentation fault      (core dumped) PYTHONFAULTHANDLER=1 python `which bikeshed` --print=plain -f spec 2>&1 > $BSLOG
```

- This function seem to be using `lxml` things, which is C, which was updated from `4.3.0` (version I was using locally) to `4.3.1` (version that is being pulled by default on travis) about 11 days ago ([commit](https://github.com/lxml/lxml/commit/642a41bdc3aae05f52ccf32981c429c7d3789f63)).
- If I update to 4.3.1 locally on my Ubuntu box, I can repro the crash deterministically.

Now, I've pushed a patch on master to pin the version to `4.3.0` for now so we can work, but it's probably not a situation that is tenable for long. 

@tabatkins, I'm pinging you here in case any of your users have the same issue, so you're aware of this problem and can communicate on a possible workaround, or skip `4.3.1` altogether. This does not look like an error in bikeshed, I think.

In any case, I sent an email to the lxml mailing list about this, I'll followup if they come up with a fix.

**Comment by padenot** [comment]
We can close this, I've pushed directly to master.

**Comment by scoder** [comment]
The crash has been resolved in lxml 4.3.2, freshly released.

**Comment by tabatkins** [comment]
Thanks for the ping, btw; I was indeed aware of it, and had already released some fixes to the install metadata to ensure that 4.3.0 was installed. I guess I could remove that now that 4.3.2 is fixed, but I'm already replacing LXML with a bespoke parser *anyway*, so whatever.

**Pull request closed without merging**
