### PR TITLE
Refining audioworklet diagram

### PR DESCRIPTION
**Pull request by hoch**
I refined the diagram for instantiation sequence. It looks more consistent with the one in the introduction section.

Preview: https://rawgit.com/hoch/web-audio-api/refining-audioworklet-diagram/index.html#AudioWorklet-Sequence

### CODE REVIEW

**Comment by padenot** [comment]
Can you clean up this branch and merge ? The diagram looks much better and does not seem to contain functional changes (only aesthetics). Thanks !

**Comment by hoch** [comment]
@padenot Not sure how to clean this up. I created this branch yesterday but somehow some commits from last December popped up.

**Comment by padenot** [comment]
@hoch, here is one way to proceed, considering only a single commit from this PR had all the relevant changes:

```sh
# Add your repo as a new remote
git remote add hoch git@github.com:hoch/web-audio-api.git
# Fetch your branches
git fetch hoch
# Get on right right branch
git checkout gh-pages
# Get a single commit from your branch, that has the new diagrams
git cherry-pick aee0f9
# Publish the commit
git push origin gh-pages
```

**Comment by padenot** [comment]
Fixed by https://github.com/WebAudio/web-audio-api/commit/3ee9b01bc2180b82ec6c02a322e2936f26110b1e.

**Comment by joeberkovitz** [comment]
@hoch I'm late to the party, but I agree this looks much better!

**Pull request closed without merging**
