### PR TITLE
Fix #444 documentation on ordering of onstatechange and oncomplete

### LINKED ISSUE #444: Ordering of onstatechange and oncomplete for OfflineAudioContext
The spec doesn't currently say, but if an offline context has specified both an onstatechange handler and an oncomplete handler, which one is executed first? Or should it be unspecified?

### PR DESCRIPTION
**Pull request by billhofmann**

### CODE REVIEW

**Comment by rtoy** [comment]
lgtm.  Don't know what's up with travis, though.

**Comment by billhofmann** [comment]
Error with Travis. @padenot ?

$ curl https://cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -o cmake-3.3.1-Linux-x86_64.tar.gz && tar xzf cmake-3.3.1-Linux-x86_64.tar.gz && rm -f cmake-3.3.1-Linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   202  100   202    0     0   3122      0 --:--:-- --:--:-- --:--:--  4488
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "curl https://cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -o cmake-3.3.1-Linux-x86_64.tar.gz && tar xzf cmake-3.3.1-Linux-x86_64.tar.gz && rm -f cmake-3.3.1-Linux-x86_64.tar.gz" failed and exited with 2 during .

**Comment by rtoy** [comment]
I created a pull request after this and it worked.  I don't know how to get
travis to rerun.

On Sat, Dec 12, 2015 at 2:06 PM, Bill Hofmann <notifications@github.com>
wrote:

> Error with Travis. @padenot <https://github.com/padenot> ?
>
> $ curl https://cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -o
> cmake-3.3.1-Linux-x86_64.tar.gz && tar xzf cmake-3.3.1-Linux-x86_64.tar.gz
> && rm -f cmake-3.3.1-Linux-x86_64.tar.gz
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 202 100 202 0 0 3122 0 --:--:-- --:--:-- --:--:-- 4488
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> The command "curl
> https://cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -o
> cmake-3.3.1-Linux-x86_64.tar.gz && tar xzf cmake-3.3.1-Linux-x86_64.tar.gz
> && rm -f cmake-3.3.1-Linux-x86_64.tar.gz" failed and exited with 2 during .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/pull/680#issuecomment-164197015>
> .
>



-- 
Ray

**Comment by billhofmann** [comment]
ok, travis is ok now, made an inconsequential change.  merging.

**Pull request merged**
