### PR TITLE
Add missing second 'new AudioContext()'

### PR DESCRIPTION
**Pull request by 0joshuaolson1**
***
<a href="https://pr-preview.s3.amazonaws.com/0joshuaolson1/web-audio-api/pull/1793.html" title="Last updated on Nov 14, 2018, 11:12 PM GMT (22d40c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/1793/8b66e51...0joshuaolson1:22d40c6.html" title="Last updated on Nov 14, 2018, 11:12 PM GMT (22d40c6)">Diff</a>

### CODE REVIEW

**Comment by padenot** [comment]
I don't understand why we would need a second context here?

**Comment by 0joshuaolson1** [comment]
I agree, but see all other code in the spec. As noted, this doesn't work in Chrome anyway.

**Comment by padenot** [comment]
There is exactly one occurrence of having two `AudioContext`, and it's a bug indeed.

The fact that it does not work on Chrome is irrelevant here, you can file a ticket on Chromium [here](https://bugs.chromium.org/p/chromium/issues/entry?template=Audio%2FVideo+Issue).

@hoch, does the above make sense? Are you aware of the Chromium bug described above?

**Comment by 0joshuaolson1** [comment]
There are two; see my [new PR](https://github.com/WebAudio/web-audio-api/pull/1794) (removing them).

**Comment by hoch** [comment]
My mistake. The line 3 in the example 15 must be removed.

**Pull request closed without merging**
