### PR TITLE
Fix compression curve diagram

### PR DESCRIPTION
**Pull request by padenot**
The knee comes after the threshold, and is added to it, so the soft knee
starts at the treshold.

### CODE REVIEW

**Comment by padenot** [comment]
https://github.com/WebAudio/web-audio-api/pull/2277/files?short_path=7b72c9b#diff-7b72c9b801345c6cd8c520be21197c028322286e8ba7ca8bd0f55ae28afc26bb shows the difference.

**Review by rtoy — APPROVED** [review]
Looks good.  What did you use to create this image?  Should the source be in the repo?  We've have the source Graffle files for all of the images that used Graffle.

**Comment by rtoy** [comment]
Not sure what's up with bikeshed.  Some intermittent data issue?

**Comment by padenot** [comment]
> Looks good. What did you use to create this image? Should the source be in the repo? We've have the source Graffle files for all of the images that used Graffle.

I used Inkscape, an SVG editor that is free software. The source is the file itself :-).

Unclear what's up with bikeshed.

**Comment by rtoy** [comment]
> > Looks good. What did you use to create this image? Should the source be in the repo? We've have the source Graffle files for all of the images that used Graffle.
> 
> I used Inkscape, an SVG editor that is free software. The source is the file itself :-).
Heh.  Ok.
> 
> Unclear what's up with bikeshed.
Yeah. I don't have this problem when I build locally.  I even updated my copy of bikeshed to the latest version just now.

**Comment by padenot** [comment]
Same, but I also retriggered the travis build, and it still fails.

**Pull request merged**
