### PR TITLE
Reformat the spec with tidy

### PR DESCRIPTION
**Pull request by padenot**

### CODE REVIEW

**Comment by rtoy** [comment]
Can you upload the new changes?

**Comment by padenot** [comment]
This is rebased against gh-pages and includes review comments. It's also split up.

**Comment by rtoy** [comment]
lgtm.

I thought you said you would add some comments on how to use this. I can't find it.

**Comment by padenot** [comment]
Hrm, I imported the wrong Makefile when rebasing...

**Comment by padenot** [comment]
I'm going ahead and merging this, since it's kind of a pain keep this massive rewrite up to date.

**Pull request merged**
