### PR TITLE
Fix #314 - sample rate in createBuffer, OfflineAudioContext

### LINKED ISSUE #314: OfflineAudioContext doesn't specify valid sample rates
The description for OfflineAudioContext doesn't mention if there are any constraints on valid sample rates.  Chrome has a limit of 44100-96000 Hz. (Apparently, this is related to the HRTF responses.)

### PR DESCRIPTION
**Pull request by billhofmann**
Note constructor arguments weren't documented - copy/paste from creatBuffer

### CODE REVIEW

**Comment by billhofmann** [comment]
Note we don't have any examples of documenting a constructor like this in the spec, since none of the other interfaces have constructors with arguments...

**Comment by billhofmann** [comment]
rtoy - not sure on your comments - do you want me to refer to createBuffer for valid sample rates, rather than the copy/paste, or shall I just merge?

**Comment by rtoy** [comment]
I would prefer you say the valid rates are the same as for AudioBuffer so that there's just the one place that specifies the valid rates.

**Comment by billhofmann** [comment]
language updated, including number of channels, to refer to createBuffer

**Comment by rtoy** [comment]
lgtm

**Pull request merged**
