### PR TITLE
Prohibit arbitrary termination of AudioWorkletGlobalScopes

### PR DESCRIPTION
**Pull request by domenic**
Part of https://github.com/w3c/css-houdini-drafts/issues/470 and https://github.com/whatwg/html/pull/6072.

***
<a href="https://pr-preview.s3.amazonaws.com/domenic/web-audio-api/pull/2266.html" title="Last updated on Oct 16, 2020, 6:03 PM UTC (ab5af97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/2266/a2ade4a...domenic:ab5af97.html" title="Last updated on Oct 16, 2020, 6:03 PM UTC (ab5af97)">Diff</a>

### CODE REVIEW

**Comment by rtoy** [comment]
Thanks for the PR.  But I see this change introduces lots of new bikeshed errors.  We'll need to get  those straightened out or update the expected-errors file to make a note of these expected failures.

**Comment by rtoy** [comment]
Or maybe that's due to an updated bikeshed.  I'll have to check....

**Comment by rtoy** [comment]
Don't know what's going on.  When I use your patch locally, I only get a new error:
```
LINE ~9787: No 'dfn' refs found for 'terminate a worklet global scope'.
```
Maybe bikeshed needs to be updated to get this new dfn?

For the other [errors that show up in Travis](https://travis-ci.com/github/WebAudio/web-audio-api/builds/190522122), I have no clue.

**Comment by domenic** [comment]
Hmm, very strange. It's exported in HTML (https://html.spec.whatwg.org/multipage/worklets.html#terminate-a-worklet-global-scope), so it should be in the Bikeshed database... maybe @tabatkins can help debug?

**Comment by tabatkins** [comment]
Yeah, I definitely see that term in the db...

```
╰╴bikeshed refs --text="terminate a worklet global scope"
type:      dfn
spec:      html
shortname: html
level:     1
status:    snapshot
url:       https://html.spec.whatwg.org/multipage/worklets.html#terminate-a-worklet-global-scope
export:    True
normative: True
for:       []
text:      terminate a worklet global scope
```

**Comment by tabatkins** [comment]
The other conflicts might be due to the lingering "official" versions of the definitions from the /TR doc, if the spec is being generated for a TR-ready status.  Let me mark worklets-1 as an ignored spec to remove that possibility.

**Comment by rtoy** [comment]
Extra weird.  My local build of bikeshed can't find "terminate a worklet global scope".  Perhaps this is related to the issue that sometimes bikeshed update can't download files.  (See https://github.com/tabatkins/bikeshed/issues/1801.)  

But my linux box can find it. (Was using my mac to test this.)

**Comment by rtoy** [comment]
Ok.  My linux box has no issues with @domenic 's PR.  Now I don't know what's up with Travis.  We now use the current git version of bikeshed for Travis CI.

**Comment by rtoy** [comment]
Well, weird.  Ask Travis to rerun and everything is fine.

So, looks good to me. :-)

**Comment by rtoy** [comment]
Could you also take a look @padenot ?

**Review by padenot — APPROVED** [review]

**Pull request merged**
