### PR TITLE
Align dfn syntax for constructors

### PR DESCRIPTION
**Pull request by dontcallmedom**
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/web-audio-api/pull/2473.html" title="Last updated on Feb 23, 2022, 10:34 AM UTC (a64c6af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/2473/7a2ca43...dontcallmedom:a64c6af.html" title="Last updated on Feb 23, 2022, 10:34 AM UTC (a64c6af)">Diff</a>

### CODE REVIEW

**Comment by padenot** [comment]
What's with this new build failure:

```
+WARNING: No 'dom-audiobuffersourcenode-constructor-audiobuffersourcenode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-channelmergernode-constructor-channelmergernode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-channelsplitternode-constructor-channelsplitternode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-constantsourcenode-constructor-constantsourcenode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-convolvernode-constructor-convolvernode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-delaynode-constructor-delaynode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-dynamicscompressornode-constructor-dynamicscompressornode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-gainnode-constructor-gainnode' ID found, skipping MDN features that would target it.
+WARNING: No 'dom-iirfilternode-constructor-iirfilternode' ID found, skipping MDN features that would target it.
```

it seems more useful to not change this, if we break this feature. Or maybe it's not quite the right markup? In any case, some `AudioNode`'s ctors are still `method` (such as the biquad).

**Review by hoch — COMMENTED** [review]
So the solution here is to specify the dom ID directly?

**Comment by dontcallmedom** [comment]
specifying the DOM id is the simplest solution; an alternative is to update the `spec_url` data in MDN browser-compat-data (e.g. https://github.com/mdn/browser-compat-data/blob/ab15b66925470ebd8b348af41fafbefaff496618/api/AudioContext.json#L110), but that would take longer to percolate through the toolchain.

**Review by hoch — APPROVED** [review]
LGTM. Thanks for tidying things up, @dontcallmedom!

**Pull request merged**
