### PR TITLE
Fix #2281: CR 2020-12-15

### LINKED ISSUE #2281: Create updated CR
**Describe the Issue**
As mentioned in last weeks teleconf, we want to make an updated CR since there were a lot of changes since the last CR.  This issue is meant to keep track of this task.

Please also remember to create a tag at the point where the CR is created so we can keep track of the exact version used, as noted in #2243.

### PR DESCRIPTION
**Pull request by rtoy**
Create a new CR for 2020-12

***
<a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/pull/2283.html" title="Last updated on Jan 19, 2021, 6:27 PM UTC (97492a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/2283/c407320...97492a2.html" title="Last updated on Jan 19, 2021, 6:27 PM UTC (97492a2)">Diff</a>

### CODE REVIEW

**Comment by rtoy** [comment]
Well, that was unexpected.  Travis fails but when I run bikeshed locally updated just now (like our Travis CI), I get no issues.

**Comment by rtoy** [comment]
@svgeesus Can you check that I made the right changes for CR?

I'll have to figure out why Travis isn't like this, but maybe it doesn't matter as long as I can build it locally myself.  The preview looks ok.

**Comment by rtoy** [comment]
Of course, this **MUST NOT** be merged to the main branch, since that's for the editor's branch.

**Review by svgeesus — APPROVED** [review]

**Comment by svgeesus** [comment]
Ok great, this is good to build now. Then I can do the pubrules check and broken link check.

**Comment by rtoy** [comment]
I think we're all set now.  bikeshed doesn't produce any new errors now.

**Comment by rtoy** [comment]
The associated tag is cr-2021-01-14, aka [97492a2311211c06fd24a04ed001afeb2ea56c7b].  The CR has been published and this PR has been updated to reflect what was actually published.

Of course, we can't merge this, but #2281 is now closed.

**Pull request closed without merging**
