### PR TITLE
Apply new GC changes to AudioWorkletNode's processing condition

### PR DESCRIPTION
**Pull request by hoch**
Fixes: #1453.

Revise the condition of Audio Worklet node that is "actively processing".

cc: @karlt

***
<a href="https://pr-preview.s3.amazonaws.com/hoch/web-audio-api/pull/1875.html" title="Last updated on Jun 3, 2019, 8:34 PM UTC (83bef39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/1875/7e24f10...hoch:83bef39.html" title="Last updated on Jun 3, 2019, 8:34 PM UTC (83bef39)">Diff</a>

### CODE REVIEW

**Comment by karlt** [comment]
This change captures the intent, thanks @hoch, but note that callable process is already required to be true for the AudioWorkletNode to be actively processing.  This can therefore be simplified further as the first of the two conditions becomes redundant.

**Comment by hoch** [comment]
So you mean "The AudioWorkletNode is actively processing" alone is good enough here?

**Comment by karlt** [comment]
Yes, and so it could be simplified to "The process() method is called synchronously by the audio rendering thread at every render quantum, if the AudioWorkletNode is actively processing."

**Comment by hoch** [comment]
That's better. Done!

**Pull request merged**
