### PR TITLE
Small typo fix in `rolloffFactor` description

### PR DESCRIPTION
**Pull request by alvov**
Changed `panningModel` to `distanceModel` in `rolloffFactor` attribute description where `linear`, `inverse` and `exponential` models are mentioned. Also added **s** to `source move`, sorry, if I'm wrong here.

### CODE REVIEW

**Comment by rtoy** [comment]
Thanks for the fix!  If possible, can you run tidy or apply the tidy fix?

**Comment by alvov** [comment]
Sure, I will update the pr after a while.

**Comment by alvov** [comment]
@rtoy done! Pardon me for not doing `make check` before creating this pr. What could possibly go wrong, I naively thought.

**Comment by rtoy** [comment]
No worries!  I forget to run tidy all the time.

**Comment by rtoy** [comment]
Hmm.  Your version of tidy unindented many `<pre>` tags. Not wrong, but not really needed.

The checks passed, so I think this is good.

**Comment by alvov** [comment]
> Your version of tidy unindented many \<pre\> tags

Sorry again, my version is 5.0.0, it actually did show some errors with `</pre>`, and most tags were unindented, so I thought that's the right way :)

Thanks a lot!

**Pull request merged**
