### PR TITLE
FIx #670 - Wording change

### LINKED ISSUE #670: Clarify what "stability" means in playbackCategory description
This was brought up on blink-dev.  In the description of AudioContextPlaybackCategory (https://webaudio.github.io/web-audio-api/#idl-def-AudioContextPlaybackCategory) we have:

    balanced	Balance audio output latency and stability/power consumption. 

What does "stability" actually mean here?

### PR DESCRIPTION
**Pull request by billhofmann**
remove confusing wording in AudioContext init

### CODE REVIEW

**Comment by billhofmann** [comment]
Stumped on why tidy failed.  I did a clone of head, changed one word, and pushed...

**Comment by rtoy** [comment]
Chris Lilley did some changes this morning.  Perhaps that's why there are so many diffs in the details.

Let me take a look....

**Comment by rtoy** [comment]
Yes, that appears to be the case.  Let me fix those.

**Comment by rtoy** [comment]
Ok. Tidy fixes in pull request #675 which has been merged.  Please try again.

**Comment by billhofmann** [comment]
eh.  abandoning

**Pull request closed without merging**
