### PR TITLE
Fix #2032:  ABSN extrapolates the last output

### LINKED ISSUE #2032: AudioBufferSourceNode: How to interpolate after last sample?
**Describe the issue**
The spec requires interpolation for playhead positions not corresponding to sampled times. Therefore, after each sample, there is an interval of duration 1/buffer.sampleRate corresponding to valid playhead positions which must be interpolated. This is also true for the interval after the last sample, but the spec doesn't specify how to produce the interpolated values for this region (since there is no next point to interpolate with).

This affects existing WPT tests: buffer-resampling.html seems to assume that the value of the last sample should be used for the whole interval, but another option is to interpolate with silence.

**Where Is It**
https://webaudio.github.io/web-audio-api/#playback-AudioBufferSourceNode -- more precisely, "Sub-sample start offsets or loop points may require additional interpolation between sample frames" does not cover the last interval described above, because it is not between sample frames. 

**Additional Information**
This is not related to looping, and in fact only applies when looping is disabled.

### PR DESCRIPTION
**Pull request by rtoy**
Update `playbackSignal` to mention that extrapolation is used to compute the output sample when the buffer is not looping and we're at the end of the buffer but need output a sample after the end of the buffer but before the next output sample frame.

***
<a href="https://pr-preview.s3.amazonaws.com/rtoy/web-audio-api/pull/2256.html" title="Last updated on Nov 6, 2020, 7:08 PM UTC (d911d4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/2256/d50c68f...rtoy:d911d4b.html" title="Last updated on Nov 6, 2020, 7:08 PM UTC (d911d4b)">Diff</a>

### CODE REVIEW

**Comment by padenot** [comment]
cc @karlt.

**Comment by padenot** [comment]
This looks sensible, but @karlt knows more about this.

**Comment by karlt** [comment]
I understand that @rtoy and I see this somewhat differently.
[sub-sample start timing](https://github.com/WebAudio/web-audio-api/issues/2032#issuecomment-708897898) and [upsampling](https://github.com/WebAudio/web-audio-api/issues/2047#issuecomment-525150837) are both situations where extrapolation would be just as useful before the first buffer sample as after the last sample, so it seems undesirable to me to describe extrapolation only after the last sample.

I would suggest just removing "between" from the text in the previous paragraph "UA-supplied algorithm that interpolates -between- sample frames in the neighborhood of position".  If "interpolates" is not considered generic enough to support values outside the provided buffer samples, then it can be replaced with "interpolates or extrapolates".  I would be happy that using "extrapolates" in this way would also include UA-specific sinc function approximations.

**Comment by rtoy** [comment]
Sorry for the delay @karlt 
> I understand that @rtoy and I see this somewhat differently.
> [sub-sample start timing](https://github.com/WebAudio/web-audio-api/issues/2032#issuecomment-708897898) and [upsampling](https://github.com/WebAudio/web-audio-api/issues/2047#issuecomment-525150837) are both situations where extrapolation would be just as useful before the first buffer sample as after the last sample, so it seems undesirable to me to describe extrapolation only after the last sample.
> 
> I would suggest just removing "between" from the text in the previous paragraph "UA-supplied algorithm that interpolates -between- sample frames in the neighborhood of position". If "interpolates" is not considered generic enough to support values outside the provided buffer samples, then it can be replaced with "interpolates or extrapolates". I would be happy that using "extrapolates" in this way would also include UA-specific sinc function approximations.

I'm fine with removing "between" as you suggest.  I'm not sure what you're suggesting for the rest of the new text, though.

I don't think sinc interpolators are forbidden. It might be unexpected if users say `start(t)` and there's non-zero and possibly audible output before time `t`.  For all the DSP work I've done, we always used casual systems and had to account for any filter delays appropriately.

**Comment by karlt** [comment]
> I'm fine with removing "between" as you suggest. I'm not sure what you're suggesting for the rest of the new text, though.

If "between" is removed, I'm suggesting that there is no need to add a new paragraph. i.e. modification to the preceding paragraph is sufficient to remove implication that interpolation (or extrapolation) happens only between samples.

**Comment by rtoy** [comment]
> > I'm fine with removing "between" as you suggest. I'm not sure what you're suggesting for the rest of the new text, though.
> 
> If "between" is removed, I'm suggesting that there is no need to add a new paragraph. i.e. modification to the preceding paragraph is sufficient to remove implication that interpolation (or extrapolation) happens only between samples.

That's fine with me.  I've made the proposed changes.

**Comment by rtoy** [comment]
@karlt says these changes are ok.  I'm going to land this now.

**Pull request merged**
