### PR TITLE
Fix #323: Add IIRFilterNode

### LINKED ISSUE #323: Biquad: Possibility to set the filters coefficients and not just Q/freq/gain
Currently it is only possible to design a filter by using the Q/freq/gain parameters.
It seems that the solution would be to show the setNormalizedCoefficients function of the biquad node on the API.

void Biquad::setNormalizedCoefficients(double b0, double b1, double b2, double a0, double a1, double a2) ->  http://dxr.mozilla.org/mozilla-central/source/content/media/webaudio/blink/Biquad.cpp

### PR DESCRIPTION
**Pull request by rtoy**
This adds a new IIRFilterNode that implements a general IIR filter.
The filter coefficients are fixed and cannot be changed.  The maximum
number of coefficients is 20.

Is "IIRFIlterNode" the desired name?  What is the limit on the number of coefficients?  Should there be any?  In the constructor, the order of the arguments is the b (numerator coefficients) and a (denominator coefficients).  Is this the correct order?

### CODE REVIEW

**Comment by mdjp** [comment]
Typo in line 781 /tranfer/transfer

**Comment by joeberkovitz** [comment]
Do we need size checking on output arrays for `getFrequencyResponse()`?

**Comment by rtoy** [comment]
Yes, we should mention constraints on the output arrays (and the input array).  BiquadFilterNode needs this too.  I'll file a separate issue on that.

**Comment by rtoy** [comment]
A couple of things I would like to change.

 * Instead of `Float32Array` args to `createIIRFilter`, I'd like `sequence<float>` instead.  Then you can simply say `createIIRFilter([1,-.9],[1])` instead of doing `new Float32Array(2)` and so on.
 * Octave and matlab's `filter` function (IIR filtering) has the arguments in the opposite order.  That is, the feedback (numerator) coefficients are the first arg, and the feedback (denominator) coefficients are the second.

**Comment by joeberkovitz** [comment]
These both sound like good changes to me: both the move to `sequence<float>` and the argument reordering to preserve the reading order of "numerator / denominator".

**Comment by rtoy** [comment]
How about making the arguments to getFrequencyResponse also be
sequence<float> too instead of Float32Array?  This makes it different from
BiquadFilterNode, but we can change BiquadFilterNode.getFrequencyResponse
to do the same since it's backward compatible.

On Mon, Aug 31, 2015 at 7:27 AM, Joe Berkovitz <notifications@github.com>
wrote:

> These both sound like good changes to me: both the move to sequence<float>
> and the argument reordering to preserve the reading order of "numerator /
> denominator".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/pull/556#issuecomment-136387647>
> .
>



-- 
Ray

**Comment by joeberkovitz** [comment]
I think that the getFrequencyResponse case seems a little different since there is no particular upper limit on the number of frequencies passed in. The array could potentially be quite large if the caller is trying to grab a high-resolution spectrum, which maybe makes this a little bit like extracting frequency response data from AnalyzerNode. So I see more of a case for the Float32Array type here...

**Comment by rtoy** [comment]
Ok.  I thought this might be a small convenience.

In any case, ES6 allows you to do Float32Array.from([1,2,3,4]), so it's not
too much of an inconvenience.

On Mon, Aug 31, 2015 at 9:52 AM, Joe Berkovitz <notifications@github.com>
wrote:

> I think that the getFrequencyResponse case seems a little different since
> there is no particular upper limit on the number of frequencies passed in.
> The array could potentially be quite large if the caller is trying to grab
> a high-resolution spectrum, which maybe makes this a little bit like
> extracting frequency response data from AnalyzerNode. So I see more of a
> case for the Float32Array type here...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebAudio/web-audio-api/pull/556#issuecomment-136427023>
> .
>



-- 
Ray

**Pull request merged**
