### PR TITLE
Fix typo in VUMeterNode sample

### PR DESCRIPTION
**Pull request by Frenzie**
***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 15, 2021, 9:29 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FWebAudio%2Fweb-audio-api%2Fe43a024bea4cb56f6dbc223f9d35dddddd4344cf%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20WebAudio/web-audio-api%232356.)._
</details>

### CODE REVIEW

**Comment by rtoy** [comment]
Thanks for the contribution.  However, since spec will soon be a Recommendation and is also a Living Standard, I think this patch can't be applied as is.  Changes like this need to be marked as a Candidate Correction.  An example can be found in #2352.  However, the actual process is still being worked out, but #2352 is probably close to what is needed.

**Comment by Frenzie** [comment]
I'm afraid I don't quite understand what you want me to do. I apologize if I didn't make it clear, but this is a piece of sample code with a typo that makes it invalid code. Instead of a `;` it should be `,` or simply nothing.

The issue you linked seems to be about a logical inconsistency in the text of itself, while the closest equivalent in regular prose would be something along the lines of: `See its' real constructor argument for a more detailed description.` → `See its real constructor argument for a more detailed description. `

**Comment by rtoy** [comment]
That's the thing.  I don't know how simple typos are supposed to be handled.  Is it a Candidate Correction?  Or is it just something we can land.

What do you think, @svgeesus?

**Comment by svgeesus** [comment]
Yes, candidate correction

**Comment by rtoy** [comment]
If you want to do the candidate correction stuff, please do so.  If not, I can take over this PR and do the changes myself.

I think this simple change is an excellent choice for showing how a candidate correction is done.

**Comment by rtoy** [comment]
Superseded by #2360.  Thanks, @Frenzie for catching this mistake!

**Comment by rtoy** [comment]
Closing this PR per https://github.com/WebAudio/web-audio-api/pull/2356#issuecomment-868825159

**Pull request closed without merging**
