### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by guest271314**
Add a LICENSE file. The text  "license" does not appear within the HTML of the current specification. See WebAudio@ae02b70, WebAudio#1527.

### CODE REVIEW

**Comment by rtoy** [comment]
Is this supposed to be empty?  It seems that way here.

**Comment by guest271314** [comment]
Yes. It was intended to be empty, for your team to fill in the blanks. Did not want to be presumptuous and include https://www.w3.org/Consortium/Legal/2015/doc-license.

**Comment by guest271314** [comment]
As "Allow edits from maintainers." is checked.

**Comment by guest271314** [comment]
Also not entire sure how the spec is "generated", or how your team would want to format (markdown?) the content of the actual text of the license.

**Comment by guest271314** [comment]
"Copyright" does not appear withing "index.bs", where just tried to substitute "license" for "document use". Have no experience using bikeshed.

**Pull request merged**
