### PR TITLE
Add missing space

### PR DESCRIPTION
**Pull request by SebastianZimmer**

### CODE REVIEW

**Comment by rtoy** [comment]
Please run tidy (`make tidy`).

Thanks.

**Comment by padenot** [comment]
This needs to be tidied, either manually (lines must be < 80 characters long) or using `make tidy`. Thanks for the patch!

**Comment by SebastianZimmer** [comment]
Will do, thanks. Thought it was <= 80 chars.

**Comment by SebastianZimmer** [comment]
Was a bit of a struggle with `tidy` on Windows. Should be fine now though.

**Comment by padenot** [comment]
Ha yes, sorry, not a lot of us use Windows.

**Comment by padenot** [comment]
Thanks for the patch !

**Pull request merged**
