### PR TITLE
Elaborate on privacy concerns

### LINKED ISSUE #2191: Restrict sounds beyond normal hearing
Breaking out this comment from https://github.com/WebAudio/web-audio-api/issues/2061, since it has not been addressed in the thread there.

> Related to the issue raised in https://github.com/WebAudio/web-audio-api/issues/1486, is there some way to restrict otherwise-unpermissioned output of sounds beyond normal hearing? As in, if you want sub- or super-sonic output, you need to jump through a hoop? (So that the exceptional case requires hoops, but the normal case doesn't.)

### PR DESCRIPTION
**Pull request by cwilso**
Fixes #2191.

***
<a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/pull/2208.html" title="Last updated on Jul 14, 2020, 3:01 PM UTC (a8b746c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebAudio/web-audio-api/2208/ef824b6...a8b746c.html" title="Last updated on Jul 14, 2020, 3:01 PM UTC (a8b746c)">Diff</a>

### CODE REVIEW

**Comment by samuelweiler** [comment]
I like it.  Thank you.

**Comment by rtoy** [comment]
Not sure why Travis CI is failing. I'll have to take a look.

**Comment by rtoy** [comment]
@cwilso Can you rebase this with the latest? It should fix the bikeshed issue.

If you can't right now, I can do it for you.

**Comment by cwilso** [comment]
@rtoy Hmm.  I thought I was doing the right rebase, but now I'm not sure, and can't fix before heading out.  Can you take over?

**Comment by rtoy** [comment]
Sure, I can take a look.

**Comment by rtoy** [comment]
This looks like a bikeshed problem.  We're getting these warnings:

```
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/html5lib/_ihatexml.py:257: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)
```

I'll need to ask Tab about these.  These weren't occurring a couple of days ago when @padenot updated the expected errors file.

**Comment by rtoy** [comment]
Weird.  My version of bikeshed (just updated now) doesn't seem to produce the same things as the version used by Travis.  Don't understand that either.

**Comment by rtoy** [comment]
According to tabatkins/bikeshed#1728, this is a bug somewhere in our spec. We'll have to hunt it down and fix it.  Very likely a recent change we made.

**Comment by cwilso** [comment]
yay!  Thank you @rtoy!

**Comment by rtoy** [comment]
No problem. Thanks for closing out one of the last few privacy issues!

**Pull request merged**
